### PR TITLE
Dynamodb kv error

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
When I try to run `make test` without setting a new `TABLE` name, I now get:

```
dynamodb-kv: callback_readmetadata: AccessDeniedException
dynamodb-kv: Error reading DynamoDB table metadata
```

which is much better than the previous message in #222, of:
```
dynamodb-kv: parsenum failed on : Invalid argument
```

**Comment by gperciva** [comment]
Hmm, maybe the second commit should have the subject
```
dynamodb-kv/capacity.c: handle error in callback_readmetadata
```

I'll leave it as-is for now, in case there's other stylistic (or other) errors.

**Comment by cperciva** [comment]
If we're going to expose extracterror it should move to dynamodb_request.c, not dynamodb_request_queue.c.

**Comment by cperciva** [comment]
I'm not sure
```
dynamodb-kv: callback_readmetadata: AccessDeniedException
dynamodb-kv: Error reading DynamoDB table metadata
```
makes sense, since `callback_readmetadata` is unnecessarily internal.  How about changing it to `DescribeTable failed: AccessDeniedException`?

**Comment by gperciva** [comment]
Updated

**Pull request merged**
