### PR TITLE
bench: don't send more requests if we're done

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by cperciva** [comment]
Hmm, this shouldn't be necessary.  Are we sending more requests without checking if we're done?  We shouldn't do that.

**Comment by gperciva** [comment]
> Are we sending more requests without checking if we're done?

Yes, we are.  I assumed that was deliberate?  Ok, I'll change it.

**Comment by gperciva** [comment]
Updated

**Comment by cperciva** [comment]
I think the reason I had e.g. "restart the RANGE request" was that if the dataset is too small we would finish reading all of it before we finished "warming up" and gathered the data we wanted.

**Pull request merged**
