### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by cperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Trivial fix for the first commit.

**Comment by cperciva** [comment]
Thanks.  No other problems you notice?

**Comment by gperciva** [comment]
No other problems that I can see, albeit I'm not really looking at the big picture.  Shall I rebase this branch?

**Comment by cperciva** [comment]
I'll take care of it, I think.  (It's good practice!)  If I have trouble I'll ask for help...

**Comment by gperciva** [comment]
BTW, I have a script that updates the dates of all commits on a branch, in case you wanted to do that here.

**Comment by cperciva** [comment]
Nah, I don't mind keeping the original dates.

**Pull request merged**
