### PR TITLE
Libcperciva build import

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This mostly unifies the build system with libcperciva.

A few remaining issues:
- importing "make test" from `Makefile.BSD` to `Makefile`: there's more things happening here, so I thought it would be cleaner to do that separately.
- cleaning up `Makefile.inc`: there's a bunch of extra lines in kivaloo (including your recently-added `MAN =` ) which should either disappear or be merged back into libcperciva.  But those lines won't influence the generated `Makefile`s, so I'll do that in a later PR.
- libcperciva's `Makefile.prog` has some lines concerning `MAN1DIR`, which

**Comment by gperciva** [comment]
Updated to include the `MAN1DIR` stuff since it's harmless.

**Comment by cperciva** [comment]
Do you want to include defining `LIBCPERCIVA_DIR` in this PR, or are you going to do that when you import the cpusupport bits?

**Comment by gperciva** [comment]
I'll probably include those.  I'm making up that branch now and I'll see how the diffs look.

**Comment by gperciva** [comment]
ready now

**Comment by cperciva** [comment]
The bits you removed from `Makefile.inc` are needed in order to make `make -f Makefile.BSD all` work.  I find this useful since it allows me to work on code without needing to keep on running `make Makefiles`.

Can you take out those last two commits?

**Comment by gperciva** [comment]
Hmm.  I'll revisit the last two commits in a later PR.  I've removed them from this one.

Ready for merge.

**Pull request merged**
